import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const PROJECT_URL = Deno.env.get("SUPABASE_URL")!;
const ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const MCP_URL = `${PROJECT_URL}/functions/v1/lef-assistant-mcp`;
const AUTH_SERVER = `${PROJECT_URL}/auth/v1`;
const cors = { "access-control-allow-origin": "*", "access-control-allow-headers": "authorization, content-type, mcp-protocol-version, mcp-session-id", "access-control-allow-methods": "GET, POST, OPTIONS" };

function json(body: unknown, status = 200, extra: Record<string, string> = {}) { return new Response(JSON.stringify(body), { status, headers: { ...cors, "content-type": "application/json", ...extra } }); }
function rpcResult(id: unknown, value: unknown) { return json({ jsonrpc: "2.0", id, result: value }); }
function rpcError(id: unknown, code: number, message: string) { return json({ jsonrpc: "2.0", id, error: { code, message } }); }
function toolText(data: unknown, isError = false) { return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], isError }; }
function oauthChallenge() { return json({ error: "authentication_required" }, 401, { "www-authenticate": `Bearer resource_metadata="${MCP_URL}/.well-known/oauth-protected-resource"` }); }

async function db(path: string, init: RequestInit = {}) {
  const response = await fetch(`${PROJECT_URL}/rest/v1/${path}`, { ...init, headers: { apikey: SERVICE_KEY, authorization: `Bearer ${SERVICE_KEY}`, "content-type": "application/json", ...(init.headers || {}) } });
  const body = await response.text();
  if (!response.ok) throw new Error(`database request failed (${response.status}): ${body.slice(0, 500)}`);
  return body ? JSON.parse(body) : null;
}

async function authenticate(req: Request) {
  const auth = req.headers.get("authorization") || "";
  if (!auth.toLowerCase().startsWith("bearer ")) return null;
  const response = await fetch(`${PROJECT_URL}/auth/v1/user`, { headers: { apikey: ANON_KEY, authorization: `Bearer ${auth.slice(7)}` } });
  if (!response.ok) return null;
  const user = await response.json();
  return { id: user.id as string, email: user.email as string };
}

const enc = (value: unknown) => encodeURIComponent(String(value));
function confirmed(args: any) { if (args?.confirmed !== true) throw new Error("explicit user confirmation is required"); }
function uuid(value: unknown, field: string) { if (typeof value !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) throw new Error(`${field} must be a UUID`); return value; }
function txt(value: unknown, field: string, max: number, required = false) { if (value == null && !required) return null; if (typeof value !== "string" || (required && !value.trim())) throw new Error(`${field} is invalid`); const result = value.trim(); if (result.length > max) throw new Error(`${field} is too long`); return result || null; }
function choice(value: unknown, field: string, values: string[]) { if (typeof value !== "string" || !values.includes(value)) throw new Error(`${field} must be one of: ${values.join(", ")}`); return value; }
function instant(value: unknown, field: string) { if (value == null) return null; if (typeof value !== "string" || Number.isNaN(Date.parse(value))) throw new Error(`${field} must be an ISO timestamp`); return new Date(value).toISOString(); }
function date(value: unknown, field: string) { if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new Error(`${field} must be YYYY-MM-DD`); const d = new Date(`${value}T12:00:00Z`); if (Number.isNaN(d.valueOf()) || d.getUTCDay() !== 1) throw new Error(`${field} must be a Monday`); return value; }
function number(value: unknown, field: string, nullable = false) { if (value == null && nullable) return null; const result = Number(value); if (!Number.isFinite(result) || result < 0) throw new Error(`${field} must be a non-negative number`); return result; }
function confidence(value: unknown) { if (value == null) return null; const result = Number(value); if (!Number.isFinite(result) || result < 0 || result > 1) throw new Error("confidence must be between 0 and 1"); return result; }
function object(value: unknown, field: string) { if (value == null) return {}; if (typeof value !== "object" || Array.isArray(value)) throw new Error(`${field} must be an object`); return value; }
function limit(value: unknown) { return Math.min(Math.max(Number(value || 50), 1), 100); }
function localDate(value: unknown, field: string) { if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new Error(`${field} must be YYYY-MM-DD`); const parsed = new Date(`${value}T12:00:00Z`); if (Number.isNaN(parsed.valueOf()) || parsed.toISOString().slice(0, 10) !== value) throw new Error(`${field} is not a valid date`); return value; }
function timezone(value: unknown) { const result = txt(value, "timezone", 100) || "America/Sao_Paulo"; try { new Intl.DateTimeFormat("en-CA", { timeZone: result }).format(new Date()); } catch { throw new Error("timezone must be a valid IANA timezone"); } return result; }
function addDays(value: string, amount: number) { const parsed = new Date(`${value}T12:00:00Z`); parsed.setUTCDate(parsed.getUTCDate() + amount); return parsed.toISOString().slice(0, 10); }
function instantLocalDay(value: unknown, zone: string) { if (typeof value !== "string" || Number.isNaN(Date.parse(value))) return null; const parts = new Intl.DateTimeFormat("en-CA", { timeZone: zone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date(value)); const part = (type: string) => parts.find((item) => item.type === type)?.value || ""; return `${part("year")}-${part("month")}-${part("day")}`; }
const checkInTypes = ["morning_plan","midday_review","proactive_intervention","end_of_day","project","weekly_sales","weekly_workspace","weekend_review","workspace_review","conversation","administration_weekly","administration_monthly","other"];
const digestFields = ["outcomes","intentions","decisions","blockers","priority_changes","unresolved_questions","follow_ups","evidence_refs"];
function hasForbiddenDigestKey(value: unknown): boolean { if (!value || typeof value !== "object") return false; if (Array.isArray(value)) return value.some(hasForbiddenDigestKey); return Object.entries(value).some(([key, nested]) => ["transcript","messages","raw_messages","verbatim_transcript"].includes(key.toLowerCase()) || hasForbiddenDigestKey(nested)); }
function reviewDigest(value: unknown) {
  const source: any = object(value, "digest");
  const unexpected=Object.keys(source).filter((key)=>key!=="schema_version"&&!digestFields.includes(key));
  if(unexpected.length)throw new Error(`digest contains unsupported fields: ${unexpected.join(", ")}`);
  if(hasForbiddenDigestKey(source))throw new Error("digest must not contain a transcript or raw messages");
  const result: any = { schema_version: 1 };
  for (const field of digestFields) {
    const items = source[field] == null ? [] : source[field];
    if (!Array.isArray(items) || items.length > 50) throw new Error(`digest.${field} must be an array with at most 50 items`);
    for (const item of items) if ((typeof item !== "string" && (typeof item !== "object" || item == null || Array.isArray(item))) || JSON.stringify(item).length > 5000) throw new Error(`digest.${field} contains an invalid or oversized item`);
    result[field] = items;
  }
  if (JSON.stringify(result).length > 50000) throw new Error("digest is too large");
  return result;
}

async function own(table: string, userId: string, value: unknown, field: string) { const id = uuid(value, field); const rows = await db(`${table}?id=eq.${id}&owner_user_id=eq.${userId}&select=*`); if (!rows.length) throw new Error(`${field.replace("_id", "")} was not found`); return rows[0]; }
async function insert(table: string, body: unknown) { const rows = await db(`${table}?select=*`, { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(body) }); return rows[0]; }
async function patch(table: string, userId: string, id: string, body: unknown) { const rows = await db(`${table}?id=eq.${id}&owner_user_id=eq.${userId}&select=*`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(body) }); return rows[0]; }

async function listMemories(args: any, userId: string) { let path = `assistant_memories?owner_user_id=eq.${userId}&select=*&order=learned_at.desc&limit=${limit(args.limit)}`; if (!args.include_expired) path += `&or=(expires_at.is.null,expires_at.gt.${enc(new Date().toISOString())})`; if (args.memory_type) path += `&memory_type=eq.${choice(args.memory_type, "memory_type", ["preference","priority","routine","work_pattern","context","decision","other"])}`; return { memories: await db(path) }; }
async function recordMemory(args: any, userId: string) {
  const sensitivity = args.sensitivity ? choice(args.sensitivity, "sensitivity", ["normal","sensitive"]) : "normal";
  const confirmationState = args.confirmation_state ? choice(args.confirmation_state, "confirmation_state", ["inferred","confirmed"]) : "inferred";
  if (sensitivity === "sensitive" || confirmationState === "confirmed" || args.source_domain !== "conversation") confirmed(args);
  const sourceDomain = args.source_domain ? choice(args.source_domain, "source_domain", ["assistant","crm","projects","administration","outlook_calendar","outlook_mail","reminders","conversation","other"]) : "conversation";
  const sourceType = txt(args.source_record_type, "source_record_type", 200);
  const sourceId = txt(args.source_external_id, "source_external_id", 500);
  if (sourceId) { const prior = await db(`assistant_memories?owner_user_id=eq.${userId}&source_domain=eq.${sourceDomain}&source_record_type=${sourceType ? `eq.${enc(sourceType)}` : "is.null"}&source_external_id=eq.${enc(sourceId)}&select=*`); if (prior.length) return { memory: prior[0], reused: true }; }
  const memory = await insert("assistant_memories", { owner_user_id: userId, memory_type: choice(args.memory_type, "memory_type", ["preference","priority","routine","work_pattern","context","decision","other"]), content: txt(args.content, "content", 10000, true), confirmation_state: confirmationState, sensitivity, source_domain: sourceDomain, source_record_type: sourceType, source_external_id: sourceId, source_url: txt(args.source_url, "source_url", 2000), confidence: confidence(args.confidence), expires_at: instant(args.expires_at, "expires_at"), context: object(args.context, "context") });
  return { memory, notice: "Recorded Assistant memory can be corrected, expired, or removed." };
}
async function updateMemory(args: any, userId: string) { confirmed(args); const row = await own("assistant_memories", userId, args.memory_id, "memory_id"); const u: any = { corrected_at: new Date().toISOString() }; if (Object.hasOwn(args,"content")) u.content=txt(args.content,"content",10000,true); if(Object.hasOwn(args,"confirmation_state"))u.confirmation_state=choice(args.confirmation_state,"confirmation_state",["inferred","confirmed"]); if(Object.hasOwn(args,"sensitivity"))u.sensitivity=choice(args.sensitivity,"sensitivity",["normal","sensitive"]); if(Object.hasOwn(args,"confidence"))u.confidence=confidence(args.confidence); if(Object.hasOwn(args,"expires_at"))u.expires_at=instant(args.expires_at,"expires_at"); return { memory: await patch("assistant_memories",userId,row.id,u) }; }
async function deleteMemory(args:any,userId:string){confirmed(args);const row=await own("assistant_memories",userId,args.memory_id,"memory_id");await db(`assistant_memories?id=eq.${row.id}&owner_user_id=eq.${userId}`,{method:"DELETE"});return{deleted:true,memory_id:row.id};}

async function listCheckIns(args:any,userId:string){let path=`assistant_check_ins?owner_user_id=eq.${userId}&select=*&order=scheduled_at.desc.nullslast,created_at.desc&limit=${limit(args.limit)}`;if(args.status)path+=`&status=eq.${choice(args.status,"status",["planned","in_progress","completed","cancelled","rescheduled"])}`;if(args.check_in_type)path+=`&check_in_type=eq.${choice(args.check_in_type,"check_in_type",checkInTypes)}`;if(args.local_day_from)path+=`&local_day=gte.${localDate(args.local_day_from,"local_day_from")}`;if(args.local_day_to)path+=`&local_day=lte.${localDate(args.local_day_to,"local_day_to")}`;return{check_ins:await db(path)};}
async function createCheckIn(args:any,userId:string){if(args.source_external_id==null||args.confirmed===true){if(args.confirmed===true)confirmed(args);}const body:any={owner_user_id:userId,check_in_type:choice(args.check_in_type,"check_in_type",checkInTypes),status:"planned",scheduled_at:instant(args.scheduled_at,"scheduled_at"),reason:txt(args.reason,"reason",2000),source_external_id:txt(args.source_external_id,"source_external_id",500),context:object(args.context,"context")};if(args.local_day)body.local_day=localDate(args.local_day,"local_day");if(args.timezone)body.timezone=timezone(args.timezone);return{check_in:await insert("assistant_check_ins",body)};}
async function updateCheckIn(args:any,userId:string){confirmed(args);const row=await own("assistant_check_ins",userId,args.check_in_id,"check_in_id");const u:any={};if(Object.hasOwn(args,"status")){u.status=choice(args.status,"status",["planned","in_progress","completed","cancelled","rescheduled"]);u.completed_at=u.status==="completed"?new Date().toISOString():null;if(u.status==="in_progress"&&!row.started_at)u.started_at=new Date().toISOString();}if(Object.hasOwn(args,"scheduled_at"))u.scheduled_at=instant(args.scheduled_at,"scheduled_at");if(Object.hasOwn(args,"reason"))u.reason=txt(args.reason,"reason",2000);if(Object.hasOwn(args,"summary"))u.summary=txt(args.summary,"summary",10000);if(Object.hasOwn(args,"rescheduled_to_id"))u.rescheduled_to_id=args.rescheduled_to_id?uuid(args.rescheduled_to_id,"rescheduled_to_id"):null;if(!Object.keys(u).length)throw new Error("no supported changes were supplied");return{check_in:await patch("assistant_check_ins",userId,row.id,u)};}

async function getReviewContinuity(args:any,userId:string){
  const scope=choice(args.scope,"scope",["daily","weekly"]);
  const zone=timezone(args.timezone);
  const start=scope==="weekly"?date(args.week_start,"week_start"):localDate(args.local_day,"local_day");
  const end=scope==="weekly"?addDays(start,6):start;
  const checkIns=await db(`assistant_check_ins?owner_user_id=eq.${userId}&local_day=gte.${start}&local_day=lte.${end}&select=*&order=local_day.asc,created_at.asc&limit=100`);
  const allCommitments=await db(`assistant_commitments?owner_user_id=eq.${userId}&select=*&order=created_at.desc&limit=100`);
  const checkInIds=new Set(checkIns.map((row:any)=>row.id));
  const periodCommitments=allCommitments.filter((row:any)=>checkInIds.has(row.check_in_id)||((instantLocalDay(row.created_at,zone)||"")>=start&&(instantLocalDay(row.created_at,zone)||"")<=end));
  const openCarryOver=allCommitments.filter((row:any)=>row.status==="confirmed"&&!periodCommitments.some((item:any)=>item.id===row.id));
  const interventions=await db(`assistant_interventions?owner_user_id=eq.${userId}&local_day=gte.${start}&local_day=lte.${end}&select=*&order=created_at.asc&limit=100`);
  const weekly=scope==="weekly"?await getWeeklyReview({week_start:start},userId):null;
  return{scope,timezone:zone,period:{start,end},check_ins:checkIns,period_commitments:periodCommitments,open_carry_over_commitments:openCarryOver,interventions,weekly_review:weekly,truncated:{check_ins:checkIns.length===100,commitments:allCommitments.length===100,interventions:interventions.length===100},domain_refresh_required:["reminders","projects","crm","administration","outlook_calendar","outlook_mail"],notice:"Review digests provide conversational continuity only. Refresh authoritative domains before advising or changing work."};
}
async function startReviewSession(args:any,userId:string){
  const type=choice(args.review_type,"review_type",["morning_plan","midday_review","end_of_day","weekly_sales","weekly_workspace","weekend_review","workspace_review","conversation"]);
  const key=txt(args.session_key,"session_key",500,true)!;
  const day=localDate(args.local_day,"local_day");
  const zone=timezone(args.timezone);
  let rows=await db(`assistant_check_ins?owner_user_id=eq.${userId}&check_in_type=eq.${type}&source_external_id=eq.${enc(key)}&select=*`);
  let reused=rows.length>0;
  if(!reused){try{rows=[await insert("assistant_check_ins",{owner_user_id:userId,check_in_type:type,status:"in_progress",scheduled_at:instant(args.scheduled_at,"scheduled_at"),started_at:new Date().toISOString(),reason:txt(args.reason,"reason",2000),source_external_id:key,local_day:day,timezone:zone,context:{...object(args.context,"context"),digest_schema_version:1,source_client:txt(args.source_client,"source_client",100)}})];}catch(error){rows=await db(`assistant_check_ins?owner_user_id=eq.${userId}&check_in_type=eq.${type}&source_external_id=eq.${enc(key)}&select=*`);if(!rows.length)throw error;reused=true;}}
  return{check_in:rows[0],reused,continuity:await getReviewContinuity({scope:"daily",local_day:day,timezone:zone},userId)};
}
async function saveReviewDigest(args:any,userId:string){
  const row=await own("assistant_check_ins",userId,args.check_in_id,"check_in_id");
  if(["cancelled","rescheduled"].includes(row.status))throw new Error("a cancelled or rescheduled review cannot receive a digest");
  const sensitivity=args.sensitivity?choice(args.sensitivity,"sensitivity",["normal","sensitive"]):"normal";
  if(sensitivity==="sensitive")confirmed(args);
  const digest=reviewDigest(args.digest);
  const now=new Date().toISOString();
  const context={...object(row.context,"stored context"),review_digest:digest,digest_sensitivity:sensitivity};
  const updated=await patch("assistant_check_ins",userId,row.id,{status:row.status==="planned"?"in_progress":row.status,started_at:row.started_at||now,summary:txt(args.summary,"summary",10000,true),digest_version:1,last_summarized_at:now,context});
  return{check_in:updated,notice:"Saved a structured, correctable review digest. No transcript or domain record was copied."};
}
async function finalizeReviewSession(args:any,userId:string){confirmed(args);const row=await own("assistant_check_ins",userId,args.check_in_id,"check_in_id");if(["cancelled","rescheduled"].includes(row.status))throw new Error("a cancelled or rescheduled review cannot be finalized");const sensitivity=args.sensitivity?choice(args.sensitivity,"sensitivity",["normal","sensitive"]):"normal";const digest=reviewDigest(args.digest);const now=new Date().toISOString();const context={...object(row.context,"stored context"),review_digest:digest,digest_sensitivity:sensitivity};return{check_in:await patch("assistant_check_ins",userId,row.id,{status:"completed",started_at:row.started_at||now,completed_at:now,summary:txt(args.summary,"summary",10000,true),digest_version:1,last_summarized_at:now,context}),notice:"Finalized the review session. Domain records remain authoritative and unchanged."};}

async function listTargets(args:any,userId:string){let path=`assistant_weekly_targets?owner_user_id=eq.${userId}&select=*&order=week_start.desc,category.asc&limit=${limit(args.limit)}`;if(args.week_start)path+=`&week_start=eq.${date(args.week_start,"week_start")}`;return{targets:await db(path)};}
async function createTarget(args:any,userId:string){confirmed(args);return{target:await insert("assistant_weekly_targets",{owner_user_id:userId,week_start:date(args.week_start,"week_start"),category:choice(args.category,"category",["sales","delivery","projects","administration","marketing","other"]),metric_key:txt(args.metric_key,"metric_key",200,true),label:txt(args.label,"label",500,true),target_value:number(args.target_value,"target_value"),unit:txt(args.unit,"unit",100,true),notes:txt(args.notes,"notes",10000)})};}
async function updateTarget(args:any,userId:string){confirmed(args);const row=await own("assistant_weekly_targets",userId,args.target_id,"target_id");const u:any={};if(Object.hasOwn(args,"target_value"))u.target_value=number(args.target_value,"target_value");if(Object.hasOwn(args,"actual_value"))u.actual_value=number(args.actual_value,"actual_value",true);if(Object.hasOwn(args,"status"))u.status=choice(args.status,"status",["active","met","missed","cancelled"]);if(Object.hasOwn(args,"evidence_quality"))u.evidence_quality=choice(args.evidence_quality,"evidence_quality",["unknown","partial","verified"]);if(Object.hasOwn(args,"notes"))u.notes=txt(args.notes,"notes",10000);if(!Object.keys(u).length)throw new Error("no supported changes were supplied");return{target:await patch("assistant_weekly_targets",userId,row.id,u)};}
async function getWeeklyReview(args:any,userId:string){const week=date(args.week_start,"week_start");const [targets,evaluations]=await Promise.all([db(`assistant_weekly_targets?owner_user_id=eq.${userId}&week_start=eq.${week}&select=*&order=category.asc,metric_key.asc`),db(`assistant_weekly_evaluations?owner_user_id=eq.${userId}&week_start=eq.${week}&select=*`)]);return{week_start:week,targets,evaluation:evaluations[0]||null};}
async function saveEvaluation(args:any,userId:string){const week=date(args.week_start,"week_start");const existing=await db(`assistant_weekly_evaluations?owner_user_id=eq.${userId}&week_start=eq.${week}&select=*`);if(args.status==="completed")confirmed(args);const body:any={status:args.status?choice(args.status,"status",["draft","completed","reopened"]):"draft",evidence_quality:args.evidence_quality?choice(args.evidence_quality,"evidence_quality",["unknown","partial","verified"]):"unknown",summary:txt(args.summary,"summary",10000),wins:txt(args.wins,"wins",10000),gaps:txt(args.gaps,"gaps",10000),recommendations:txt(args.recommendations,"recommendations",10000),context:object(args.context,"context")};body.completed_at=body.status==="completed"?new Date().toISOString():null;if(existing.length)return{evaluation:await patch("assistant_weekly_evaluations",userId,existing[0].id,body),updated:true};return{evaluation:await insert("assistant_weekly_evaluations",{...body,owner_user_id:userId,week_start:week}),updated:false};}

async function listCommitments(args:any,userId:string){let path=`assistant_commitments?owner_user_id=eq.${userId}&select=*&order=due_at.asc.nullslast,created_at.desc&limit=${limit(args.limit)}`;if(args.status)path+=`&status=eq.${choice(args.status,"status",["confirmed","completed","cancelled"])}`;return{commitments:await db(path)};}
async function createCommitment(args:any,userId:string){confirmed(args);const sourceDomain=choice(args.source_domain,"source_domain",["assistant","crm","projects","administration","outlook_calendar","outlook_mail","reminders","conversation","other"]);const sourceType=txt(args.source_record_type,"source_record_type",200);const sourceId=txt(args.source_external_id,"source_external_id",500);const checkInId=args.check_in_id?uuid(args.check_in_id,"check_in_id"):null;if(checkInId)await own("assistant_check_ins",userId,checkInId,"check_in_id");if(sourceId){const prior=await db(`assistant_commitments?owner_user_id=eq.${userId}&source_domain=eq.${sourceDomain}&source_record_type=${sourceType?`eq.${enc(sourceType)}`:"is.null"}&source_external_id=eq.${enc(sourceId)}&select=*`);if(prior.length)return{commitment:prior[0],reused:true};}return{commitment:await insert("assistant_commitments",{owner_user_id:userId,check_in_id:checkInId,title:txt(args.title,"title",500,true),details:txt(args.details,"details",10000),due_at:instant(args.due_at,"due_at"),confirmed_at:new Date().toISOString(),authority_domain:choice(args.authority_domain,"authority_domain",["assistant","crm","projects","administration","outlook_calendar","outlook_mail","reminders","other"]),source_domain:sourceDomain,source_record_type:sourceType,source_external_id:sourceId,source_url:txt(args.source_url,"source_url",2000),context:object(args.context,"context")})};}
async function updateCommitment(args:any,userId:string){confirmed(args);const row=await own("assistant_commitments",userId,args.commitment_id,"commitment_id");const u:any={};if(Object.hasOwn(args,"title"))u.title=txt(args.title,"title",500,true);if(Object.hasOwn(args,"details"))u.details=txt(args.details,"details",10000);if(Object.hasOwn(args,"due_at"))u.due_at=instant(args.due_at,"due_at");if(Object.hasOwn(args,"status")){u.status=choice(args.status,"status",["confirmed","completed","cancelled"]);u.completed_at=u.status==="completed"?new Date().toISOString():null;}if(!Object.keys(u).length)throw new Error("no supported changes were supplied");return{commitment:await patch("assistant_commitments",userId,row.id,u)};}

const attentionTriggerTypes=["event","periodic","morning_plan","end_of_day","weekly_sales","manual"];
const attentionDecisions=["no_action","pending_delivery","suppressed","failed"];
const interventionStatuses=["pending","delivered","acknowledged","completed","scheduled","snoozed","blocked","rejected","failed","cancelled"];
const authorityDomains=["assistant","crm","projects","administration","outlook_calendar","outlook_mail","reminders","other"];

async function recordAttentionEvaluation(args:any,userId:string){
  const triggerKey=txt(args.trigger_key,"trigger_key",500,true)!;
  const prior=await db(`assistant_attention_evaluations?owner_user_id=eq.${userId}&trigger_key=eq.${enc(triggerKey)}&select=*`);
  if(prior.length)return{evaluation:prior[0],reused:true};
  const evaluation=await insert("assistant_attention_evaluations",{owner_user_id:userId,trigger_type:choice(args.trigger_type,"trigger_type",attentionTriggerTypes),trigger_key:triggerKey,evaluated_at:instant(args.evaluated_at,"evaluated_at")||new Date().toISOString(),window_start:instant(args.window_start,"window_start"),window_end:instant(args.window_end,"window_end"),timezone:txt(args.timezone,"timezone",100)||"America/Sao_Paulo",decision:choice(args.decision,"decision",attentionDecisions),reason:txt(args.reason,"reason",4000),evidence_quality:args.evidence_quality?choice(args.evidence_quality,"evidence_quality",["unknown","partial","verified"]):"unknown",context:object(args.context,"context")});
  return{evaluation,reused:false};
}

async function createIntervention(args:any,userId:string){
  const transactionKey=txt(args.transaction_key,"transaction_key",500,true)!;
  const prior=await db(`assistant_interventions?owner_user_id=eq.${userId}&transaction_key=eq.${enc(transactionKey)}&select=*`);
  if(prior.length)return{intervention:prior[0],reused:true};
  const evaluation=await own("assistant_attention_evaluations",userId,args.evaluation_id,"evaluation_id");
  const checkInId=args.check_in_id?uuid(args.check_in_id,"check_in_id"):null;
  if(checkInId)await own("assistant_check_ins",userId,checkInId,"check_in_id");
  if(!/^\d{4}-\d{2}-\d{2}$/.test(String(args.local_day||"")))throw new Error("local_day must be YYYY-MM-DD");
  const items=Array.isArray(args.items)?args.items:[];
  if(items.length<1||items.length>20)throw new Error("items must contain between 1 and 20 referenced items");
  const intervention=await insert("assistant_interventions",{owner_user_id:userId,evaluation_id:evaluation.id,check_in_id:checkInId,transaction_key:transactionKey,title:txt(args.title,"title",500,true),reason:txt(args.reason,"reason",4000,true),suggested_next_step:txt(args.suggested_next_step,"suggested_next_step",4000),urgency:args.urgency?choice(args.urgency,"urgency",["low","normal","high","urgent"]):"normal",tone_level:args.tone_level?choice(args.tone_level,"tone_level",["helpful","direct","confronting"]):"helpful",status:"pending",not_before:instant(args.not_before,"not_before"),expires_at:instant(args.expires_at,"expires_at"),next_review_at:instant(args.next_review_at,"next_review_at"),local_day:String(args.local_day),daily_sequence:Math.min(Math.max(Number(args.daily_sequence||1),1),99),exception_reason:txt(args.exception_reason,"exception_reason",4000),context:object(args.context,"context")});
  try{
    const rows=items.map((item:any,index:number)=>({owner_user_id:userId,intervention_id:intervention.id,authority_domain:choice(item.authority_domain,`items[${index}].authority_domain`,authorityDomains),source_record_type:txt(item.source_record_type,`items[${index}].source_record_type`,200,true),source_external_id:txt(item.source_external_id,`items[${index}].source_external_id`,500,true),title:txt(item.title,`items[${index}].title`,500,true),summary:txt(item.summary,`items[${index}].summary`,4000),due_at:instant(item.due_at,`items[${index}].due_at`),importance_rank:Math.min(Math.max(Number(item.importance_rank||50),1),100),context:object(item.context,`items[${index}].context`)}));
    await db("assistant_intervention_items",{method:"POST",body:JSON.stringify(rows)});
    await insert("assistant_intervention_events",{owner_user_id:userId,intervention_id:intervention.id,event_type:"created",actor_type:"assistant",details:{trigger_type:evaluation.trigger_type}});
    return{intervention,items:rows,reused:false};
  }catch(error){await db(`assistant_interventions?id=eq.${intervention.id}&owner_user_id=eq.${userId}`,{method:"DELETE"});throw error;}
}

async function listInterventions(args:any,userId:string){
  let path=`assistant_interventions?owner_user_id=eq.${userId}&select=*&order=created_at.desc&limit=${limit(args.limit)}`;
  if(args.status)path+=`&status=eq.${choice(args.status,"status",interventionStatuses)}`;
  const interventions=await db(path);
  if(!interventions.length)return{interventions:[]};
  const ids=interventions.map((row:any)=>row.id).join(",");
  const [items,events]=await Promise.all([db(`assistant_intervention_items?owner_user_id=eq.${userId}&intervention_id=in.(${ids})&select=*&order=importance_rank.asc`),db(`assistant_intervention_events?owner_user_id=eq.${userId}&intervention_id=in.(${ids})&select=*&order=occurred_at.asc`)]);
  return{interventions:interventions.map((row:any)=>({...row,items:items.filter((item:any)=>item.intervention_id===row.id),events:events.filter((event:any)=>event.intervention_id===row.id)}))};
}

async function recordDelivery(args:any,userId:string){
  const intervention=await own("assistant_interventions",userId,args.intervention_id,"intervention_id");
  const result=choice(args.delivery_result,"delivery_result",["delivered","failed","suppressed"]);
  const status=result==="delivered"?"delivered":result==="failed"?"failed":"pending";
  const now=new Date().toISOString();
  const updated=await patch("assistant_interventions",userId,intervention.id,{status,delivered_at:result==="delivered"?now:null,next_review_at:instant(args.next_review_at,"next_review_at"),outcome_note:txt(args.note,"note",4000)});
  await insert("assistant_intervention_events",{owner_user_id:userId,intervention_id:intervention.id,event_type:result==="delivered"?"delivered":result==="failed"?"delivery_failed":"suppressed",actor_type:"system",details:{channel:txt(args.channel,"channel",100)||"chatgpt",reason:txt(args.reason,"reason",2000)}});
  return{intervention:updated};
}

async function recordInterventionOutcome(args:any,userId:string){
  confirmed(args);
  const intervention=await own("assistant_interventions",userId,args.intervention_id,"intervention_id");
  const outcome=choice(args.outcome,"outcome",["acknowledged","completed","scheduled","snoozed","blocked","rejected"]);
  const updated=await patch("assistant_interventions",userId,intervention.id,{status:outcome,next_review_at:instant(args.next_review_at,"next_review_at"),outcome_note:txt(args.note,"note",4000)});
  await insert("assistant_intervention_events",{owner_user_id:userId,intervention_id:intervention.id,event_type:outcome,actor_type:"user",details:{note:txt(args.note,"note",4000),scheduled_for:instant(args.scheduled_for,"scheduled_for"),next_review_at:instant(args.next_review_at,"next_review_at")}});
  return{intervention:updated};
}

const scheduleTypes=["periodic","fixed_check_in","calendar_offset","deadline_offset","reminder_review","other"];
const scheduleStatuses=["active","paused","cancelled"];
async function listAttentionSchedules(args:any,userId:string){let path=`assistant_attention_schedules?owner_user_id=eq.${userId}&select=*&order=created_at.asc&limit=${limit(args.limit)}`;if(args.status)path+=`&status=eq.${choice(args.status,"status",scheduleStatuses)}`;return{schedules:await db(path)};}
async function saveAttentionSchedule(args:any,userId:string){confirmed(args);const body:any={name:txt(args.name,"name",500,true),schedule_type:choice(args.schedule_type,"schedule_type",scheduleTypes),status:args.status?choice(args.status,"status",scheduleStatuses):"active",timezone:txt(args.timezone,"timezone",100)||"America/Sao_Paulo",schedule_expression:txt(args.schedule_expression,"schedule_expression",500),next_run_at:instant(args.next_run_at,"next_run_at"),offset_minutes:args.offset_minutes==null?null:Math.trunc(Number(args.offset_minutes)),source_authority:args.source_authority?choice(args.source_authority,"source_authority",authorityDomains):null,source_record_type:txt(args.source_record_type,"source_record_type",200),source_external_id:txt(args.source_external_id,"source_external_id",500),eligibility_policy:object(args.eligibility_policy,"eligibility_policy")};if(body.offset_minutes!=null&&(body.offset_minutes < -10080||body.offset_minutes>10080))throw new Error("offset_minutes is out of range");if(args.schedule_id){const prior=await own("assistant_attention_schedules",userId,args.schedule_id,"schedule_id");return{schedule:await patch("assistant_attention_schedules",userId,prior.id,body),updated:true};}return{schedule:await insert("assistant_attention_schedules",{owner_user_id:userId,...body}),updated:false};}
async function listScheduledDeliveries(args:any,userId:string){let path=`assistant_scheduled_deliveries?owner_user_id=eq.${userId}&select=*&order=deliver_at.asc&limit=${limit(args.limit)}`;if(args.status)path+=`&status=eq.${choice(args.status,"status",["queued","claimed","delivered","failed","cancelled","suppressed","expired"])}`;return{deliveries:await db(path)};}
async function enqueueScheduledDelivery(args:any,userId:string){const key=txt(args.delivery_key,"delivery_key",500,true)!;const prior=await db(`assistant_scheduled_deliveries?owner_user_id=eq.${userId}&delivery_key=eq.${enc(key)}&select=*`);if(prior.length)return{delivery:prior[0],reused:true};const scheduleId=args.schedule_id?uuid(args.schedule_id,"schedule_id"):null;if(scheduleId)await own("assistant_attention_schedules",userId,scheduleId,"schedule_id");const interventionId=args.intervention_id?uuid(args.intervention_id,"intervention_id"):null;if(interventionId)await own("assistant_interventions",userId,interventionId,"intervention_id");const deliverAt=instant(args.deliver_at,"deliver_at");if(!deliverAt)throw new Error("deliver_at is required");const delivery=await insert("assistant_scheduled_deliveries",{owner_user_id:userId,schedule_id:scheduleId,intervention_id:interventionId,delivery_key:key,delivery_channel:"teams",status:"queued",deliver_at:deliverAt,available_at:instant(args.available_at,"available_at")||deliverAt,expires_at:instant(args.expires_at,"expires_at"),source_authority:choice(args.source_authority,"source_authority",authorityDomains),source_record_type:txt(args.source_record_type,"source_record_type",200,true),source_external_id:txt(args.source_external_id,"source_external_id",500,true),source_version:txt(args.source_version,"source_version",500),rendered_title:txt(args.rendered_title,"rendered_title",500,true),rendered_body:txt(args.rendered_body,"rendered_body",10000,true),discussion_target:object(args.discussion_target,"discussion_target"),payload:object(args.payload,"payload"),max_attempts:Math.min(Math.max(Math.trunc(Number(args.max_attempts||5)),1),20)});return{delivery,reused:false};}
async function cancelScheduledDelivery(args:any,userId:string){confirmed(args);const row=await own("assistant_scheduled_deliveries",userId,args.delivery_id,"delivery_id");if(row.status==="delivered")throw new Error("a delivered item cannot be cancelled");return{delivery:await patch("assistant_scheduled_deliveries",userId,row.id,{status:"cancelled",claimed_at:null,claimed_by:null,last_error:txt(args.reason,"reason",2000)})};}

const c={confirmed:{type:"boolean",const:true}};
const tools=[
{name:"list_assistant_memories",description:"List current Assistant-owned memories for the authenticated user.",inputSchema:{type:"object",properties:{memory_type:{type:"string",enum:["preference","priority","routine","work_pattern","context","decision","other"]},include_expired:{type:"boolean"},limit:{type:"integer",minimum:1,maximum:100}}}},
{name:"record_assistant_memory",description:"Record visible, correctable work context. Sensitive, confirmed, or non-conversation records require explicit confirmation.",inputSchema:{type:"object",required:["memory_type","content"],properties:{memory_type:{type:"string",enum:["preference","priority","routine","work_pattern","context","decision","other"]},content:{type:"string",maxLength:10000},confirmation_state:{type:"string",enum:["inferred","confirmed"]},sensitivity:{type:"string",enum:["normal","sensitive"]},source_domain:{type:"string",enum:["assistant","crm","projects","administration","outlook_calendar","outlook_mail","reminders","conversation","other"]},source_record_type:{type:"string",maxLength:200},source_external_id:{type:"string",maxLength:500},source_url:{type:"string",maxLength:2000},confidence:{type:"number",minimum:0,maximum:1},expires_at:{type:"string",format:"date-time"},context:{type:"object"},...c}}},
{name:"update_assistant_memory",description:"Correct, confirm, or expire a memory after explicit confirmation.",inputSchema:{type:"object",required:["memory_id","confirmed"],properties:{memory_id:{type:"string",format:"uuid"},content:{type:"string",maxLength:10000},confirmation_state:{type:"string",enum:["inferred","confirmed"]},sensitivity:{type:"string",enum:["normal","sensitive"]},confidence:{type:["number","null"]},expires_at:{type:["string","null"],format:"date-time"},...c}}},
{name:"delete_assistant_memory",description:"Remove an Assistant memory after explicit confirmation.",inputSchema:{type:"object",required:["memory_id","confirmed"],properties:{memory_id:{type:"string",format:"uuid"},...c}}},
{name:"list_check_ins",description:"List Assistant accountability check-ins, optionally constrained to a local-day range.",inputSchema:{type:"object",properties:{check_in_type:{type:"string",enum:checkInTypes},status:{type:"string",enum:["planned","in_progress","completed","cancelled","rescheduled"]},local_day_from:{type:"string",format:"date"},local_day_to:{type:"string",format:"date"},limit:{type:"integer",minimum:1,maximum:100}}}},
{name:"create_check_in",description:"Create a planned check-in with an optional schedule, local day, and reason.",inputSchema:{type:"object",required:["check_in_type"],properties:{check_in_type:{type:"string",enum:checkInTypes},scheduled_at:{type:"string",format:"date-time"},local_day:{type:"string",format:"date"},timezone:{type:"string",maxLength:100},reason:{type:"string",maxLength:2000},source_external_id:{type:"string",maxLength:500},context:{type:"object"},...c}}},
{name:"update_check_in",description:"Complete, cancel, or explicitly reschedule a check-in after confirmation.",inputSchema:{type:"object",required:["check_in_id","confirmed"],properties:{check_in_id:{type:"string",format:"uuid"},status:{type:"string",enum:["planned","in_progress","completed","cancelled","rescheduled"]},scheduled_at:{type:["string","null"],format:"date-time"},reason:{type:["string","null"],maxLength:2000},summary:{type:["string","null"],maxLength:10000},rescheduled_to_id:{type:["string","null"],format:"uuid"},...c}}},
{name:"start_review_session",description:"Call at the beginning of every substantive LEF planning, review, or accountability conversation. Idempotently starts or resumes a cross-chat session and returns today's Assistant continuity. Fresh domain facts must still be retrieved from their owning tools.",inputSchema:{type:"object",required:["review_type","session_key","local_day"],properties:{review_type:{type:"string",enum:["morning_plan","midday_review","end_of_day","weekly_sales","weekly_workspace","weekend_review","workspace_review","conversation"]},session_key:{type:"string",maxLength:500},local_day:{type:"string",format:"date"},timezone:{type:"string",maxLength:100},scheduled_at:{type:["string","null"],format:"date-time"},reason:{type:"string",maxLength:2000},source_client:{type:"string",maxLength:100},context:{type:"object"}}}},
{name:"save_review_digest",description:"Call progressively when a user confirms an outcome, intention, decision, blocker, priority change, or follow-up, and before a substantive review may end. Saves minimal cross-chat continuity; never include transcripts, raw messages, unrelated speech, or copied domain datasets. Sensitive digests require explicit confirmation.",inputSchema:{type:"object",required:["check_in_id","summary","digest"],properties:{check_in_id:{type:"string",format:"uuid"},summary:{type:"string",maxLength:10000},sensitivity:{type:"string",enum:["normal","sensitive"]},digest:{type:"object",properties:{outcomes:{type:"array",maxItems:50,items:{}},intentions:{type:"array",maxItems:50,items:{}},decisions:{type:"array",maxItems:50,items:{}},blockers:{type:"array",maxItems:50,items:{}},priority_changes:{type:"array",maxItems:50,items:{}},unresolved_questions:{type:"array",maxItems:50,items:{}},follow_ups:{type:"array",maxItems:50,items:{}},evidence_refs:{type:"array",maxItems:50,items:{}}},additionalProperties:false},...c}}},
{name:"get_review_continuity",description:"Retrieve daily or Monday-to-Sunday Assistant review continuity and open carry-over commitments. This is not a substitute for fresh reads from authoritative domains.",inputSchema:{type:"object",required:["scope"],properties:{scope:{type:"string",enum:["daily","weekly"]},local_day:{type:"string",format:"date"},week_start:{type:"string",format:"date"},timezone:{type:"string",maxLength:100}}}},
{name:"finalize_review_session",description:"Save the final structured digest and complete a review session after explicit confirmation. This does not mutate domain records.",inputSchema:{type:"object",required:["check_in_id","summary","digest","confirmed"],properties:{check_in_id:{type:"string",format:"uuid"},summary:{type:"string",maxLength:10000},sensitivity:{type:"string",enum:["normal","sensitive"]},digest:{type:"object",properties:{outcomes:{type:"array",maxItems:50,items:{}},intentions:{type:"array",maxItems:50,items:{}},decisions:{type:"array",maxItems:50,items:{}},blockers:{type:"array",maxItems:50,items:{}},priority_changes:{type:"array",maxItems:50,items:{}},unresolved_questions:{type:"array",maxItems:50,items:{}},follow_ups:{type:"array",maxItems:50,items:{}},evidence_refs:{type:"array",maxItems:50,items:{}}},additionalProperties:false},...c}}},
{name:"list_weekly_targets",description:"List adjustable weekly targets and their evidence quality.",inputSchema:{type:"object",properties:{week_start:{type:"string",format:"date"},limit:{type:"integer",minimum:1,maximum:100}}}},
{name:"create_weekly_target",description:"Create an agreed weekly target after explicit confirmation.",inputSchema:{type:"object",required:["week_start","category","metric_key","label","target_value","unit","confirmed"],properties:{week_start:{type:"string",format:"date"},category:{type:"string",enum:["sales","delivery","projects","administration","marketing","other"]},metric_key:{type:"string",maxLength:200},label:{type:"string",maxLength:500},target_value:{type:"number",minimum:0},unit:{type:"string",maxLength:100},notes:{type:"string",maxLength:10000},...c}}},
{name:"update_weekly_target",description:"Record actuals, evidence quality, status, or a revised target after explicit confirmation.",inputSchema:{type:"object",required:["target_id","confirmed"],properties:{target_id:{type:"string",format:"uuid"},target_value:{type:"number",minimum:0},actual_value:{type:["number","null"],minimum:0},status:{type:"string",enum:["active","met","missed","cancelled"]},evidence_quality:{type:"string",enum:["unknown","partial","verified"]},notes:{type:["string","null"],maxLength:10000},...c}}},
{name:"get_weekly_review",description:"Get targets and the Assistant evaluation for one Monday-based week.",inputSchema:{type:"object",required:["week_start"],properties:{week_start:{type:"string",format:"date"}}}},
{name:"save_weekly_evaluation",description:"Save a visible evidence-aware draft evaluation, or complete it after explicit confirmation.",inputSchema:{type:"object",required:["week_start"],properties:{week_start:{type:"string",format:"date"},status:{type:"string",enum:["draft","completed","reopened"]},evidence_quality:{type:"string",enum:["unknown","partial","verified"]},summary:{type:"string",maxLength:10000},wins:{type:"string",maxLength:10000},gaps:{type:"string",maxLength:10000},recommendations:{type:"string",maxLength:10000},context:{type:"object"},...c}}},
{name:"list_commitments",description:"List confirmed cross-domain commitments without treating Assistant snapshots as source authority.",inputSchema:{type:"object",properties:{status:{type:"string",enum:["confirmed","completed","cancelled"]},limit:{type:"integer",minimum:1,maximum:100}}}},
{name:"create_commitment",description:"Record a confirmed sourced commitment after explicit confirmation, optionally linked to the review in which it was made.",inputSchema:{type:"object",required:["title","authority_domain","source_domain","confirmed"],properties:{check_in_id:{type:["string","null"],format:"uuid"},title:{type:"string",maxLength:500},details:{type:"string",maxLength:10000},due_at:{type:"string",format:"date-time"},authority_domain:{type:"string",enum:["assistant","crm","projects","administration","outlook_calendar","outlook_mail","reminders","other"]},source_domain:{type:"string",enum:["assistant","crm","projects","administration","outlook_calendar","outlook_mail","reminders","conversation","other"]},source_record_type:{type:"string",maxLength:200},source_external_id:{type:"string",maxLength:500},source_url:{type:"string",maxLength:2000},context:{type:"object"},...c}}},
{name:"update_commitment",description:"Update, complete, or cancel a commitment reference after explicit confirmation.",inputSchema:{type:"object",required:["commitment_id","confirmed"],properties:{commitment_id:{type:"string",format:"uuid"},title:{type:"string",maxLength:500},details:{type:["string","null"],maxLength:10000},due_at:{type:["string","null"],format:"date-time"},status:{type:"string",enum:["confirmed","completed","cancelled"]},...c}}}
,{name:"record_attention_evaluation",description:"Idempotently record one owner-scoped attention evaluation. This stores the decision and evidence summary but does not deliver a notification.",inputSchema:{type:"object",required:["trigger_type","trigger_key","decision"],properties:{trigger_type:{type:"string",enum:attentionTriggerTypes},trigger_key:{type:"string",maxLength:500},evaluated_at:{type:"string",format:"date-time"},window_start:{type:["string","null"],format:"date-time"},window_end:{type:["string","null"],format:"date-time"},timezone:{type:"string",maxLength:100},decision:{type:"string",enum:attentionDecisions},reason:{type:"string",maxLength:4000},evidence_quality:{type:"string",enum:["unknown","partial","verified"]},context:{type:"object"}}}},
{name:"create_attention_intervention",description:"Idempotently create one pending intervention with one to twenty cross-domain references. Does not deliver a notification or mutate source domains.",inputSchema:{type:"object",required:["evaluation_id","transaction_key","title","reason","local_day","items"],properties:{evaluation_id:{type:"string",format:"uuid"},check_in_id:{type:["string","null"],format:"uuid"},transaction_key:{type:"string",maxLength:500},title:{type:"string",maxLength:500},reason:{type:"string",maxLength:4000},suggested_next_step:{type:"string",maxLength:4000},urgency:{type:"string",enum:["low","normal","high","urgent"]},tone_level:{type:"string",enum:["helpful","direct","confronting"]},not_before:{type:["string","null"],format:"date-time"},expires_at:{type:["string","null"],format:"date-time"},next_review_at:{type:["string","null"],format:"date-time"},local_day:{type:"string",format:"date"},daily_sequence:{type:"integer",minimum:1,maximum:99},exception_reason:{type:"string",maxLength:4000},context:{type:"object"},items:{type:"array",minItems:1,maxItems:20,items:{type:"object",required:["authority_domain","source_record_type","source_external_id","title"],properties:{authority_domain:{type:"string",enum:authorityDomains},source_record_type:{type:"string",maxLength:200},source_external_id:{type:"string",maxLength:500},title:{type:"string",maxLength:500},summary:{type:"string",maxLength:4000},due_at:{type:["string","null"],format:"date-time"},importance_rank:{type:"integer",minimum:1,maximum:100},context:{type:"object"}}}}}}},
{name:"list_attention_interventions",description:"List owner-scoped interventions with their referenced items and event history.",inputSchema:{type:"object",properties:{status:{type:"string",enum:interventionStatuses},limit:{type:"integer",minimum:1,maximum:100}}}},
{name:"record_intervention_delivery",description:"Record a ChatGPT delivery, failure, or policy suppression. This does not itself send a notification.",inputSchema:{type:"object",required:["intervention_id","delivery_result"],properties:{intervention_id:{type:"string",format:"uuid"},delivery_result:{type:"string",enum:["delivered","failed","suppressed"]},channel:{type:"string",maxLength:100},reason:{type:"string",maxLength:2000},note:{type:"string",maxLength:4000},next_review_at:{type:["string","null"],format:"date-time"}}}},
{name:"record_intervention_outcome",description:"Record the user's structured response to an intervention after explicit confirmation. Underlying domain records remain unchanged.",inputSchema:{type:"object",required:["intervention_id","outcome","confirmed"],properties:{intervention_id:{type:"string",format:"uuid"},outcome:{type:"string",enum:["acknowledged","completed","scheduled","snoozed","blocked","rejected"]},note:{type:"string",maxLength:4000},scheduled_for:{type:["string","null"],format:"date-time"},next_review_at:{type:["string","null"],format:"date-time"},...c}}}
,{name:"list_attention_schedules",description:"List owner-scoped LEF attention schedules.",inputSchema:{type:"object",properties:{status:{type:"string",enum:scheduleStatuses},limit:{type:"integer",minimum:1,maximum:100}}}},
{name:"save_attention_schedule",description:"Create or update an LEF attention schedule after explicit confirmation.",inputSchema:{type:"object",required:["name","schedule_type","confirmed"],properties:{schedule_id:{type:"string",format:"uuid"},name:{type:"string",maxLength:500},schedule_type:{type:"string",enum:scheduleTypes},status:{type:"string",enum:scheduleStatuses},timezone:{type:"string",maxLength:100},schedule_expression:{type:["string","null"],maxLength:500},next_run_at:{type:["string","null"],format:"date-time"},offset_minutes:{type:["integer","null"],minimum:-10080,maximum:10080},source_authority:{type:["string","null"],enum:authorityDomains},source_record_type:{type:["string","null"],maxLength:200},source_external_id:{type:["string","null"],maxLength:500},eligibility_policy:{type:"object"},...c}}},
{name:"list_scheduled_deliveries",description:"List durable owner-scoped notification deliveries and their current state.",inputSchema:{type:"object",properties:{status:{type:"string",enum:["queued","claimed","delivered","failed","cancelled","suppressed","expired"]},limit:{type:"integer",minimum:1,maximum:100}}}},
{name:"enqueue_scheduled_delivery",description:"Idempotently queue a rendered owner-facing Teams notification. This never sends customer communication or mutates the source domain.",inputSchema:{type:"object",required:["delivery_key","deliver_at","source_authority","source_record_type","source_external_id","rendered_title","rendered_body"],properties:{schedule_id:{type:["string","null"],format:"uuid"},intervention_id:{type:["string","null"],format:"uuid"},delivery_key:{type:"string",maxLength:500},deliver_at:{type:"string",format:"date-time"},available_at:{type:["string","null"],format:"date-time"},expires_at:{type:["string","null"],format:"date-time"},source_authority:{type:"string",enum:authorityDomains},source_record_type:{type:"string",maxLength:200},source_external_id:{type:"string",maxLength:500},source_version:{type:["string","null"],maxLength:500},rendered_title:{type:"string",maxLength:500},rendered_body:{type:"string",maxLength:10000},discussion_target:{type:"object"},payload:{type:"object"},max_attempts:{type:"integer",minimum:1,maximum:20}}}},
{name:"cancel_scheduled_delivery",description:"Cancel a not-yet-delivered notification after explicit confirmation.",inputSchema:{type:"object",required:["delivery_id","confirmed"],properties:{delivery_id:{type:"string",format:"uuid"},reason:{type:"string",maxLength:2000},...c}}}
];

async function callTool(name:string,args:any,user:any){
if(name==="list_assistant_memories")return listMemories(args||{},user.id);if(name==="record_assistant_memory")return recordMemory(args||{},user.id);if(name==="update_assistant_memory")return updateMemory(args||{},user.id);if(name==="delete_assistant_memory")return deleteMemory(args||{},user.id);
if(name==="list_check_ins")return listCheckIns(args||{},user.id);if(name==="create_check_in")return createCheckIn(args||{},user.id);if(name==="update_check_in")return updateCheckIn(args||{},user.id);
if(name==="start_review_session")return startReviewSession(args||{},user.id);if(name==="save_review_digest")return saveReviewDigest(args||{},user.id);if(name==="get_review_continuity")return getReviewContinuity(args||{},user.id);if(name==="finalize_review_session")return finalizeReviewSession(args||{},user.id);
if(name==="list_weekly_targets")return listTargets(args||{},user.id);if(name==="create_weekly_target")return createTarget(args||{},user.id);if(name==="update_weekly_target")return updateTarget(args||{},user.id);if(name==="get_weekly_review")return getWeeklyReview(args||{},user.id);if(name==="save_weekly_evaluation")return saveEvaluation(args||{},user.id);
if(name==="list_commitments")return listCommitments(args||{},user.id);if(name==="create_commitment")return createCommitment(args||{},user.id);if(name==="update_commitment")return updateCommitment(args||{},user.id);
if(name==="record_attention_evaluation")return recordAttentionEvaluation(args||{},user.id);if(name==="create_attention_intervention")return createIntervention(args||{},user.id);if(name==="list_attention_interventions")return listInterventions(args||{},user.id);if(name==="record_intervention_delivery")return recordDelivery(args||{},user.id);if(name==="record_intervention_outcome")return recordInterventionOutcome(args||{},user.id);
if(name==="list_attention_schedules")return listAttentionSchedules(args||{},user.id);if(name==="save_attention_schedule")return saveAttentionSchedule(args||{},user.id);if(name==="list_scheduled_deliveries")return listScheduledDeliveries(args||{},user.id);if(name==="enqueue_scheduled_delivery")return enqueueScheduledDelivery(args||{},user.id);if(name==="cancel_scheduled_delivery")return cancelScheduledDelivery(args||{},user.id);throw new Error(`unknown tool: ${name}`);}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});const url=new URL(req.url);const metadata={resource:MCP_URL,authorization_servers:[AUTH_SERVER],scopes_supported:["email"],bearer_methods_supported:["header"]};if(req.method==="GET"&&url.pathname.endsWith("/.well-known/oauth-protected-resource"))return json(metadata);if(req.method==="GET")return json({name:"LEF Assistant MCP",status:"authentication_required",...metadata,resource_metadata:`${MCP_URL}/.well-known/oauth-protected-resource`});if(req.method!=="POST")return json({error:"method_not_allowed"},405);const user=await authenticate(req);if(!user)return oauthChallenge();let body:any;try{body=await req.json();}catch{return rpcError(null,-32700,"Parse error");}const{id,method,params}=body||{};if(method==="initialize")return rpcResult(id,{protocolVersion:params?.protocolVersion||"2025-06-18",capabilities:{tools:{listChanged:false}},serverInfo:{name:"lef-assistant",version:"1.1.0"}});if(method==="notifications/initialized")return new Response(null,{status:202,headers:cors});if(method==="ping")return rpcResult(id,{});if(method==="tools/list")return rpcResult(id,{tools});if(method==="tools/call"){try{return rpcResult(id,toolText(await callTool(params?.name,params?.arguments||{},user)));}catch(error){return rpcResult(id,toolText({error:error instanceof Error?error.message:String(error)},true));}}return rpcError(id??null,-32601,"Method not found");});
