// Owns popup DOM element references only.
// Do not add event bindings or flow/business logic here.
(function initPopupDom(globalObj) {
  const PopupDom = {
    focusEl: document.getElementById("focus"),
    messageLanguageEl: document.getElementById("messageLanguage"),
    inviteLanguageEl: document.getElementById("inviteLanguage"),
    freePromptLanguageEl: document.getElementById("freePromptLanguage"),
    campaignSelectEl: document.getElementById("campaignSelect"),
    campaignComboToggleEl: document.getElementById("campaignComboToggle"),
    campaignComboPanelEl: document.getElementById("campaignComboPanel"),
    campaignComboInputEl: document.getElementById("campaignComboInput"),
    campaignComboListEl: document.getElementById("campaignComboList"),
    renameCampaignBtnEl: document.getElementById("renameCampaign"),
    renameCampaignRowEl: document.getElementById("renameCampaignRow"),
    renameCampaignNameEl: document.getElementById("renameCampaignName"),
    saveRenameCampaignBtnEl: document.getElementById("saveRenameCampaign"),
    cancelRenameCampaignBtnEl: document.getElementById("cancelRenameCampaign"),
    newCampaignRowEl: document.getElementById("newCampaignRow"),
    toggleNewCampaignBtnEl: document.getElementById("toggleNewCampaign"),
    newCampaignNameEl: document.getElementById("newCampaignName"),
    addCampaignBtnEl: document.getElementById("addCampaign"),
    cancelNewCampaignBtnEl: document.getElementById("cancelNewCampaign"),
    linkedCampaignsListEl: document.getElementById("linkedCampaignsList"),
    firstMessageAdditionalPromptEl: document.getElementById(
      "firstMessageAdditionalPrompt",
    ),
    generateFirstMessageBtnEl: document.getElementById("generateFirstMessage"),
    markMessageSentBtnEl:
      document.getElementById("markFirstMessageSent") ||
      document.getElementById("markMessageSent"),
    copyFirstMessageBtnEl: document.getElementById("copyFirstMessage"),
    saveFirstMessageIconEl: document.getElementById("saveFirstMessageIcon"),
    initialMessageSectionEl: document.getElementById("initialMessageSection"),
    firstMessagePreviewSectionEl: document.getElementById(
      "firstMessagePreviewSection",
    ),
    acceptedModeEl: document.getElementById("acceptedMode"),
    firstMessageSentModeEl: document.getElementById("firstMessageSentMode"),
    followupSectionEl: document.getElementById("followupSection"),
    followupObjectiveEl: document.getElementById("followupObjective"),
    includeStrategyEl: document.getElementById("includeStrategy"),
    generateFollowupBtnEl: document.getElementById("generateFollowup"),
    footerStatusEl: document.getElementById("commFooterText"),
    followupPreviewEl: document.getElementById("followupPreview"),
    copyFollowupBtnEl: document.getElementById("copyFollowup"),
    freePromptInputEl: document.getElementById("freePromptInput"),
    freePromptIncludeProfileEl: document.getElementById(
      "freePromptIncludeProfile",
    ),
    freePromptIncludeStrategyEl: document.getElementById(
      "freePromptIncludeStrategy",
    ),
    generateFreePromptBtnEl: document.getElementById("generateFreePrompt"),
    freePromptPreviewEl: document.getElementById("freePromptPreview"),
    copyFreePromptBtnEl: document.getElementById("copyFreePrompt"),
    previewEl: document.getElementById("preview"),
    firstMessagePreviewEl: document.getElementById("firstMessagePreview"),
    copyInviteIconEl: document.getElementById("copyInviteIcon"),
    saveInviteBtnEl: document.getElementById("saveInviteBtn"),
    openSidePanelBtnEl: document.getElementById("openSidePanel"),
    detailPersonNameEl: document.getElementById("detailPersonName"),
    detailCompanyEl: document.getElementById("detailCompany"),
    detailEmployeeNumberEl: document.getElementById("detailEmployeeNumber"),
    detailHeadlineEl: document.getElementById("detailHeadline"),
    detailCommentsEl: document.getElementById("detailComments"),
    detailCityEl: document.getElementById("detailCity"),
    detailItMembersEl: document.getElementById("detailItMembers"),
    detailCompanyLabelEl: document.getElementById("detailCompanyLabel"),
    detailEmployeeNumberLabelEl: document.getElementById(
      "detailEmployeeNumberLabel",
    ),
    detailHeadlineLabelEl: document.getElementById("detailHeadlineLabel"),
    detailCommentsLabelEl: document.getElementById("detailCommentsLabel"),
    detailCityLabelEl: document.getElementById("detailCityLabel"),
    detailItMembersLabelEl: document.getElementById("detailItMembersLabel"),
    companyExistingLinkSectionEl: document.getElementById(
      "companyExistingLinkSection",
    ),
    companyExistingLinkInputEl: document.getElementById("companyExistingLinkInput"),
    companyExistingLinkStatusEl: document.getElementById(
      "companyExistingLinkStatus",
    ),
    companyExistingLinkButtonEl: document.getElementById(
      "companyExistingLinkButton",
    ),
    companyExistingLinkOptionsEl: document.getElementById(
      "companyExistingLinkOptions",
    ),
    companyPeopleSectionEl: document.getElementById("companyPeopleSection"),
    companyPeopleListEl: document.getElementById("companyPeopleList"),
    companyProfileTabsRowEl: document.getElementById("companyProfileTabsRow"),
    companyPersonsTabBtnEl: document.getElementById("companyPersonsTabBtn"),
    companyNotesTabBtnEl: document.getElementById("companyNotesTabBtn"),
    companyCampaignControlsEl: document.getElementById("companyCampaignControls"),
    companyLinkedCampaignsListEl: document.getElementById("companyLinkedCampaignsList"),
    companyCampaignSelectEl: document.getElementById("companyCampaignSelect"),
    companyCampaignComboToggleEl: document.getElementById("companyCampaignComboToggle"),
    companyCampaignComboPanelEl: document.getElementById("companyCampaignComboPanel"),
    companyCampaignComboInputEl: document.getElementById("companyCampaignComboInput"),
    companyCampaignComboListEl: document.getElementById("companyCampaignComboList"),
    companyRenameCampaignBtnEl: document.getElementById("companyRenameCampaign"),
    companyRenameCampaignRowEl: document.getElementById("companyRenameCampaignRow"),
    companyRenameCampaignNameEl: document.getElementById("companyRenameCampaignName"),
    companySaveRenameCampaignBtnEl: document.getElementById(
      "companySaveRenameCampaign",
    ),
    companyCancelRenameCampaignBtnEl: document.getElementById(
      "companyCancelRenameCampaign",
    ),
    companyToggleNewCampaignBtnEl: document.getElementById(
      "companyToggleNewCampaign",
    ),
    companyNewCampaignRowEl: document.getElementById("companyNewCampaignRow"),
    companyNewCampaignNameEl: document.getElementById("companyNewCampaignName"),
    companyAddCampaignBtnEl: document.getElementById("companyAddCampaign"),
    companyCancelNewCampaignBtnEl: document.getElementById(
      "companyCancelNewCampaign",
    ),
    enrichProfileBtnEl: document.getElementById("enrichProfileBtn"),
    editProfileBtnEl: document.getElementById("editProfileBtn"),
    saveProfileFieldsBtnEl: document.getElementById("saveProfileFieldsBtn"),
    cancelProfileEditBtnEl: document.getElementById("cancelProfileEditBtn"),
    acceptCompanySuggestionBtnEl: document.getElementById(
      "acceptCompanySuggestionBtn",
    ),
    companyLinkedRowEl: document.getElementById("companyLinkedRow"),
    companyLinkedNameEl: document.getElementById("companyLinkedName"),
    companyLinkedEmployeeNumberEl: document.getElementById(
      "companyLinkedEmployeeNumber",
    ),
    companyLinkSearchInputEl: document.getElementById("companyLinkSearchInput"),
    companyLinkedIndicatorEl: document.getElementById("companyLinkedIndicator"),
    companyLinkSearchOptionsEl: document.getElementById("companyLinkSearchOptions"),
    companyQuickLinkBtn: document.getElementById("companyQuickLinkBtn"),
    companySuggestionWarningEl: document.getElementById("companySuggestionWarning"),
    personNotRegisteredStateEl: document.getElementById("personNotRegisteredState"),
    companyUrlMismatchBannerEl: document.getElementById("companyUrlMismatchBanner"),
    campaignGroupEl: document.getElementById("campaignGroup"),
    campaignDividerEl: document.getElementById("campaignDivider"),
    statusDividerEl: document.getElementById("statusDivider"),
    detailTabsDividerEl: document.getElementById("detailTabsDivider"),
    detailTabsRowEl: document.getElementById("detailTabsRow"),
    detailNotesTabBtnEl: document.getElementById("detailNotesTabBtn"),
    detailPromptsTabBtnEl: document.getElementById("detailPromptsTabBtn"),
    detailNotesPanelEl: document.getElementById("detailNotesPanel"),
    detailPromptsPanelEl: document.getElementById("detailPromptsPanel"),
    notesFilterCompanyEl: document.getElementById("notesFilterCompany"),
    notesFilterPersonEl: document.getElementById("notesFilterPerson"),
    addNoteBtnEl: document.getElementById("addNoteBtn"),
    notesStatusEl: document.getElementById("notesStatus"),
    notesListEl: document.getElementById("notesList"),
    statusStepperEl: document.getElementById("statusStepper"),
    stepRegisterEl: document.getElementById("step-register"),
    stepInvitedEl: document.getElementById("step-invited"),
    stepAcceptedEl: document.getElementById("step-accepted"),
    stepFirstMessageSentEl: document.getElementById("step-first-message-sent"),
    stepperUnderlayEl: document.getElementById("stepperUnderlay"),
    messageCountBadgeEl: document.getElementById("messageCountBadge"),
    messageCountControlsEl: document.getElementById("messageCountControls"),
    messageCountDecrementEl: document.getElementById("messageCountDecrement"),
    messageCountIncrementEl: document.getElementById("messageCountIncrement"),
    stepMessageRespondedEl: document.getElementById("step-message-responded"),
    detailInviteSectionEl: document.getElementById("detailInviteSection"),
    detailMessageMountEl: document.getElementById("detailMessageMount"),
    tabFreePromptEl: document.getElementById("tabFreePrompt"),
    tabMainBtn: document.getElementById("tabMainBtn"),
    tabMessageBtn: document.getElementById("tabMessageBtn"),
    tabOverviewBtn: document.getElementById("tabOverviewBtn"),
    tabConfigBtn: document.getElementById("tabConfigBtn"),
    tabSupabaseAuthBtn: document.getElementById("tabSupabaseAuthBtn"),
    tabMain: document.getElementById("tabMain"),
    tabMessage: document.getElementById("tabMessage"),
    tabOverview: document.getElementById("tabOverview"),
    tabConfig: document.getElementById("tabConfig"),
    tabSupabaseAuth: document.getElementById("tabSupabaseAuth"),
    configGeneralTabBtnEl: document.getElementById("configGeneralTabBtn"),
    configSupabaseTabBtnEl: document.getElementById("configSupabaseTabBtn"),
    configGeneralPanelEl: document.getElementById("configGeneralPanel"),
    authInnerSignupBtnEl: document.getElementById("authInnerSignupBtn"),
    authInnerLoginBtnEl: document.getElementById("authInnerLoginBtn"),
    supabaseAuthFormsEl: document.getElementById("supabaseAuthForms"),
    authSignupPanelEl: document.getElementById("authSignupPanel"),
    authLoginPanelEl: document.getElementById("authLoginPanel"),
    supabaseSignupNameEl: document.getElementById("supabaseSignupName"),
    supabaseSignupEmailEl: document.getElementById("supabaseSignupEmail"),
    supabaseSignupPasswordEl: document.getElementById("supabaseSignupPassword"),
    supabaseSignupBtnEl: document.getElementById("supabaseSignupBtn"),
    supabaseLoginEmailEl: document.getElementById("supabaseLoginEmail"),
    supabaseLoginPasswordEl: document.getElementById("supabaseLoginPassword"),
    supabaseLoginBtnEl: document.getElementById("supabaseLoginBtn"),
    supabaseResetPasswordBtnEl: document.getElementById("supabaseResetPasswordBtn"),
    supabaseLoggedInPanelEl: document.getElementById("supabaseLoggedInPanel"),
    supabaseUserEmailEl: document.getElementById("supabaseUserEmail"),
    supabaseLogoutBtnEl: document.getElementById("supabaseLogoutBtn"),
    filterCampaignEl: document.getElementById("filterCampaign"),
    overviewArchivedFilterEl: document.getElementById("overviewArchivedFilter"),
    overviewStatusFilterEl: document.getElementById("overviewStatusFilter"),
    filterAcceptedEl: document.getElementById("filterAccepted"),
    overviewSearchEl: document.getElementById("overviewSearch"),
    overviewSearchClearBtnEl: document.getElementById("overviewSearchClear"),
    overviewTbodyEl: document.getElementById("overviewTbody"),
    overviewPageSizeEl: document.getElementById("overviewPageSize"),
    overviewPrevBtnEl: document.getElementById("overviewPrevBtn"),
    overviewNextBtnEl: document.getElementById("overviewNextBtn"),
    overviewCountLabelEl: document.getElementById("overviewCountLabel"),
    overviewTableEl: document.querySelector("#tabOverview .overview-table"),
    companyOverviewTableEl: document.getElementById("companyOverviewTable"),
    listPersonsTabBtnEl: document.getElementById("listPersonsTabBtn"),
    listCompaniesTabBtnEl: document.getElementById("listCompaniesTabBtn"),
    personsListPanelEl: document.getElementById("personsListPanel"),
    companiesListPanelEl: document.getElementById("companiesListPanel"),
    companyArchivedFilterEl: document.getElementById("companyArchivedFilter"),
    companyCampaignFilterEl: document.getElementById("companyCampaignFilter"),
    companySearchEl: document.getElementById("companySearch"),
    companySearchClearBtnEl: document.getElementById("companySearchClear"),
    companyOverviewTbodyEl: document.getElementById("companyOverviewTbody"),
    companyOverviewPageSizeEl: document.getElementById("companyOverviewPageSize"),
    companyOverviewPrevBtnEl: document.getElementById("companyOverviewPrevBtn"),
    companyOverviewNextBtnEl: document.getElementById("companyOverviewNextBtn"),
    companyOverviewCountLabelEl: document.getElementById("companyOverviewCountLabel"),
  };

  globalObj.PopupDom = Object.freeze(PopupDom);
})(typeof globalThis !== "undefined" ? globalThis : self);
