
create table if not exists public.crm_reminders (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 1 and 300),
  details text,
  status text not null default 'open'
    check (status in ('open','snoozed','completed','cancelled')),
  due_at timestamptz,
  next_review_at timestamptz not null default now(),
  snoozed_until timestamptz,
  completed_at timestamptz,
  priority_override text
    check (priority_override is null or priority_override in ('low','normal','high','urgent')),
  inferred_priority smallint
    check (inferred_priority is null or inferred_priority between 1 and 5),
  inferred_reason text,
  inference_confidence numeric(4,3)
    check (inference_confidence is null or inference_confidence between 0 and 1),
  assessed_at timestamptz,
  last_surfaced_at timestamptz,
  surface_count integer not null default 0 check (surface_count >= 0),
  contact_id uuid references public.linkedin_invitations(id) on delete set null,
  company_id uuid references public.company(company_id) on delete set null,
  deal_id uuid references public.deal(deal_id) on delete set null,
  source_note_id bigint references public.note(note_id) on delete set null,
  source_type text not null default 'manual'
    check (source_type in ('manual','note','gmail','calendar','linkedin','whatsapp','meeting','other')),
  source_external_id text,
  source_url text,
  context jsonb not null default '{}'::jsonb check (jsonb_typeof(context) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (snoozed_until is null or status = 'snoozed'),
  check (completed_at is null or status = 'completed')
);

create unique index if not exists crm_reminders_owner_source_unique
  on public.crm_reminders(owner_user_id, source_type, source_external_id)
  where source_external_id is not null;

create index if not exists crm_reminders_owner_review_idx
  on public.crm_reminders(owner_user_id, next_review_at)
  where status in ('open','snoozed');

create index if not exists crm_reminders_owner_due_idx
  on public.crm_reminders(owner_user_id, due_at)
  where status in ('open','snoozed');

create index if not exists crm_reminders_contact_idx on public.crm_reminders(contact_id);
create index if not exists crm_reminders_company_idx on public.crm_reminders(company_id);
create index if not exists crm_reminders_deal_idx on public.crm_reminders(deal_id);

drop trigger if exists trg_crm_reminders_updated_at on public.crm_reminders;
create trigger trg_crm_reminders_updated_at
before update on public.crm_reminders
for each row execute function public.set_updated_at();

alter table public.crm_reminders enable row level security;
revoke all on public.crm_reminders from anon;
grant select, insert, update, delete on public.crm_reminders to authenticated;
grant all on public.crm_reminders to service_role;

drop policy if exists crm_reminders_select_own on public.crm_reminders;
create policy crm_reminders_select_own on public.crm_reminders
for select to authenticated
using ((select auth.uid()) = owner_user_id);

drop policy if exists crm_reminders_insert_own on public.crm_reminders;
create policy crm_reminders_insert_own on public.crm_reminders
for insert to authenticated
with check ((select auth.uid()) = owner_user_id);

drop policy if exists crm_reminders_update_own on public.crm_reminders;
create policy crm_reminders_update_own on public.crm_reminders
for update to authenticated
using ((select auth.uid()) = owner_user_id)
with check ((select auth.uid()) = owner_user_id);

drop policy if exists crm_reminders_delete_own on public.crm_reminders;
create policy crm_reminders_delete_own on public.crm_reminders
for delete to authenticated
using ((select auth.uid()) = owner_user_id);

create table if not exists public.crm_reminder_events (
  id bigint generated by default as identity primary key,
  reminder_id uuid not null references public.crm_reminders(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null
    check (event_type in ('created','assessed','surfaced','deferred','snoozed','completed','reopened','cancelled','updated')),
  event_data jsonb not null default '{}'::jsonb check (jsonb_typeof(event_data) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists crm_reminder_events_owner_created_idx
  on public.crm_reminder_events(owner_user_id, created_at desc);
create index if not exists crm_reminder_events_reminder_idx
  on public.crm_reminder_events(reminder_id, created_at desc);

alter table public.crm_reminder_events enable row level security;
revoke all on public.crm_reminder_events from anon;
grant select, insert on public.crm_reminder_events to authenticated;
grant all on public.crm_reminder_events to service_role;

drop policy if exists crm_reminder_events_select_own on public.crm_reminder_events;
create policy crm_reminder_events_select_own on public.crm_reminder_events
for select to authenticated
using ((select auth.uid()) = owner_user_id);

drop policy if exists crm_reminder_events_insert_own on public.crm_reminder_events;
create policy crm_reminder_events_insert_own on public.crm_reminder_events
for insert to authenticated
with check (
  (select auth.uid()) = owner_user_id
  and exists (
    select 1 from public.crm_reminders r
    where r.id = reminder_id and r.owner_user_id = (select auth.uid())
  )
);
;
