create table public.project_items (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('idea', 'project')),
  parent_project_id uuid null,
  title text not null check (btrim(title) <> ''),
  details text null,
  project_status text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_items_kind_status_check check (
    (kind = 'idea' and project_status is null)
    or
    (kind = 'project' and project_status in ('active', 'paused', 'completed', 'cancelled'))
  ),
  constraint project_items_not_own_parent check (parent_project_id is null or parent_project_id <> id),
  constraint project_items_owner_identity_unique unique (id, owner_user_id),
  constraint project_items_parent_owner_fk
    foreign key (parent_project_id, owner_user_id)
    references public.project_items(id, owner_user_id)
    on delete restrict
);

create table public.project_actions (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid not null,
  title text not null check (btrim(title) <> ''),
  details text null,
  status text not null default 'open' check (status in ('open', 'completed', 'cancelled')),
  due_at timestamptz null,
  reminder_id uuid null references public.crm_reminders(id) on delete set null,
  completed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_actions_status_completed_check check (
    (status = 'completed' and completed_at is not null)
    or
    (status <> 'completed' and completed_at is null)
  ),
  constraint project_actions_owner_identity_unique unique (id, owner_user_id),
  constraint project_actions_project_owner_fk
    foreign key (project_id, owner_user_id)
    references public.project_items(id, owner_user_id)
    on delete restrict
);

create table public.project_progress_memories (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid not null,
  summary text not null check (btrim(summary) <> ''),
  source_type text not null default 'conversation' check (source_type in ('conversation', 'check_in', 'manual')),
  source_external_id text null,
  confidence numeric null check (confidence is null or (confidence >= 0 and confidence <= 1)),
  recorded_at timestamptz not null default now(),
  corrected_at timestamptz null,
  expires_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_progress_memories_project_owner_fk
    foreign key (project_id, owner_user_id)
    references public.project_items(id, owner_user_id)
    on delete cascade
);

create table public.project_events (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  project_item_id uuid not null,
  event_type text not null check (event_type in ('created', 'updated', 'promoted', 'demoted', 'status_changed')),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now(),
  constraint project_events_item_owner_fk
    foreign key (project_item_id, owner_user_id)
    references public.project_items(id, owner_user_id)
    on delete cascade
);

create index project_items_owner_kind_status_idx
  on public.project_items(owner_user_id, kind, project_status);
create index project_items_parent_idx on public.project_items(parent_project_id);
create index project_actions_owner_status_due_idx
  on public.project_actions(owner_user_id, status, due_at);
create index project_actions_project_idx on public.project_actions(project_id);
create unique index project_actions_reminder_unique
  on public.project_actions(reminder_id)
  where reminder_id is not null;
create index project_progress_memories_project_recorded_idx
  on public.project_progress_memories(project_id, recorded_at desc);
create unique index project_progress_memories_source_unique
  on public.project_progress_memories(owner_user_id, source_type, source_external_id)
  where source_external_id is not null;
create index project_events_item_created_idx
  on public.project_events(project_item_id, created_at desc);

create or replace function public.validate_project_item_hierarchy()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  parent_row public.project_items;
begin
  if tg_op = 'UPDATE' and old.kind = 'project' and new.kind = 'idea' and exists (
    select 1 from public.project_items child
    where child.parent_project_id = new.id
      and child.kind = 'project'
  ) then
    raise exception 'Demote child projects before demoting their parent project';
  end if;

  if new.parent_project_id is null then
    return new;
  end if;

  select * into parent_row
  from public.project_items
  where id = new.parent_project_id
    and owner_user_id = new.owner_user_id;

  if not found or parent_row.kind <> 'project' then
    raise exception 'Parent must be an owned project';
  end if;

  if new.kind = 'project' and parent_row.parent_project_id is not null then
    raise exception 'Projects support at most two hierarchy levels';
  end if;

  return new;
end;
$$;

create trigger trg_project_items_validate_hierarchy
before insert or update of kind, parent_project_id, owner_user_id
on public.project_items
for each row execute function public.validate_project_item_hierarchy();

create or replace function public.validate_project_action_parent()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if not exists (
    select 1 from public.project_items p
    where p.id = new.project_id
      and p.owner_user_id = new.owner_user_id
      and p.kind = 'project'
  ) then
    raise exception 'Action parent must be an owned project';
  end if;
  return new;
end;
$$;

create trigger trg_project_actions_validate_parent
before insert or update of project_id, owner_user_id
on public.project_actions
for each row execute function public.validate_project_action_parent();

create or replace function public.project_set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_project_items_updated_at
before update on public.project_items
for each row execute function public.project_set_updated_at();
create trigger trg_project_actions_updated_at
before update on public.project_actions
for each row execute function public.project_set_updated_at();
create trigger trg_project_progress_memories_updated_at
before update on public.project_progress_memories
for each row execute function public.project_set_updated_at();

create or replace function public.record_project_item_event()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  event_name text;
begin
  if tg_op = 'INSERT' then
    event_name := 'created';
  elsif old.kind = 'idea' and new.kind = 'project' then
    event_name := 'promoted';
  elsif old.kind = 'project' and new.kind = 'idea' then
    event_name := 'demoted';
  elsif old.project_status is distinct from new.project_status then
    event_name := 'status_changed';
  else
    event_name := 'updated';
  end if;

  insert into public.project_events(owner_user_id, project_item_id, event_type, payload)
  values (
    new.owner_user_id,
    new.id,
    event_name,
    jsonb_build_object(
      'old_kind', case when tg_op = 'UPDATE' then old.kind else null end,
      'new_kind', new.kind,
      'old_status', case when tg_op = 'UPDATE' then old.project_status else null end,
      'new_status', new.project_status
    )
  );
  return new;
end;
$$;

create trigger trg_project_items_record_event
after insert or update on public.project_items
for each row execute function public.record_project_item_event();

create or replace function public.handle_project_demotion()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if old.kind = 'project' and new.kind = 'idea' then
    update public.project_actions
    set status = 'cancelled'
    where project_id = new.id
      and owner_user_id = new.owner_user_id
      and status = 'open';
  end if;
  return new;
end;
$$;

create trigger trg_project_items_handle_demotion
after update of kind on public.project_items
for each row execute function public.handle_project_demotion();

create or replace function public.sync_project_action_reminder()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  reminder_row public.crm_reminders;
  reminder_status text;
  event_name text;
  reminder_found boolean := false;
begin
  if new.status = 'completed' then
    new.completed_at := coalesce(new.completed_at, now());
    reminder_status := 'completed';
  elsif new.status = 'cancelled' then
    new.completed_at := null;
    reminder_status := 'cancelled';
  else
    new.completed_at := null;
    reminder_status := 'open';
  end if;

  if new.due_at is null then
    if new.reminder_id is not null then
      update public.crm_reminders
      set status = 'cancelled', completed_at = null
      where id = new.reminder_id and owner_user_id = new.owner_user_id
      returning * into reminder_row;
      if found then
        insert into public.crm_reminder_events(reminder_id, owner_user_id, event_type, payload)
        values (new.reminder_id, new.owner_user_id, 'cancelled', jsonb_build_object('reason', 'project_action_due_date_removed'));
      end if;
    end if;
    return new;
  end if;

  if new.reminder_id is not null then
    select * into reminder_row
    from public.crm_reminders
    where id = new.reminder_id and owner_user_id = new.owner_user_id;
    reminder_found := found;
  end if;

  if not reminder_found then
    insert into public.crm_reminders (
      owner_user_id, title, details, status, due_at, next_review_at,
      completed_at, source_type, source_external_id, context
    ) values (
      new.owner_user_id,
      new.title,
      new.details,
      reminder_status,
      new.due_at,
      new.due_at,
      case when reminder_status = 'completed' then new.completed_at else null end,
      'other',
      'project_action:' || new.id::text,
      jsonb_build_object('project_action_id', new.id, 'project_id', new.project_id)
    )
    returning * into reminder_row;
    new.reminder_id := reminder_row.id;
    insert into public.crm_reminder_events(reminder_id, owner_user_id, event_type, payload)
    values (reminder_row.id, new.owner_user_id, 'created', jsonb_build_object('source', 'project_action'));
  else
    event_name := case
      when reminder_row.status in ('completed', 'cancelled') and reminder_status = 'open' then 'reopened'
      when reminder_status = 'completed' then 'completed'
      when reminder_status = 'cancelled' then 'cancelled'
      else 'updated'
    end;
    update public.crm_reminders
    set title = new.title,
        details = new.details,
        status = reminder_status,
        due_at = new.due_at,
        next_review_at = case when reminder_status = 'open' then least(new.due_at, coalesce(next_review_at, new.due_at)) else next_review_at end,
        snoozed_until = case when reminder_status = 'open' then null else snoozed_until end,
        completed_at = case when reminder_status = 'completed' then new.completed_at else null end,
        context = coalesce(context, '{}'::jsonb) || jsonb_build_object('project_action_id', new.id, 'project_id', new.project_id)
    where id = new.reminder_id and owner_user_id = new.owner_user_id;
    insert into public.crm_reminder_events(reminder_id, owner_user_id, event_type, payload)
    values (new.reminder_id, new.owner_user_id, event_name, jsonb_build_object('source', 'project_action'));
  end if;

  return new;
end;
$$;

create trigger trg_project_actions_sync_reminder
before insert or update of title, details, status, due_at, owner_user_id, project_id
on public.project_actions
for each row execute function public.sync_project_action_reminder();

alter table public.project_items enable row level security;
alter table public.project_actions enable row level security;
alter table public.project_progress_memories enable row level security;
alter table public.project_events enable row level security;

revoke all on public.project_items, public.project_actions, public.project_progress_memories, public.project_events from anon;
grant select, insert, update, delete on public.project_items, public.project_actions, public.project_progress_memories to authenticated;
grant select on public.project_events to authenticated;
grant all on public.project_items, public.project_actions, public.project_progress_memories, public.project_events to service_role;

create policy project_items_select_own on public.project_items for select to authenticated
using ((select auth.uid()) = owner_user_id);
create policy project_items_insert_own on public.project_items for insert to authenticated
with check ((select auth.uid()) = owner_user_id);
create policy project_items_update_own on public.project_items for update to authenticated
using ((select auth.uid()) = owner_user_id)
with check ((select auth.uid()) = owner_user_id);
create policy project_items_delete_own on public.project_items for delete to authenticated
using ((select auth.uid()) = owner_user_id);

create policy project_actions_select_own on public.project_actions for select to authenticated
using ((select auth.uid()) = owner_user_id);
create policy project_actions_insert_own on public.project_actions for insert to authenticated
with check ((select auth.uid()) = owner_user_id);
create policy project_actions_update_own on public.project_actions for update to authenticated
using ((select auth.uid()) = owner_user_id)
with check ((select auth.uid()) = owner_user_id);
create policy project_actions_delete_own on public.project_actions for delete to authenticated
using ((select auth.uid()) = owner_user_id);

create policy project_progress_memories_select_own on public.project_progress_memories for select to authenticated
using ((select auth.uid()) = owner_user_id);
create policy project_progress_memories_insert_own on public.project_progress_memories for insert to authenticated
with check ((select auth.uid()) = owner_user_id);
create policy project_progress_memories_update_own on public.project_progress_memories for update to authenticated
using ((select auth.uid()) = owner_user_id)
with check ((select auth.uid()) = owner_user_id);
create policy project_progress_memories_delete_own on public.project_progress_memories for delete to authenticated
using ((select auth.uid()) = owner_user_id);

create policy project_events_select_own on public.project_events for select to authenticated
using ((select auth.uid()) = owner_user_id);

revoke all on function public.validate_project_item_hierarchy() from public, anon, authenticated;
revoke all on function public.validate_project_action_parent() from public, anon, authenticated;
revoke all on function public.project_set_updated_at() from public, anon, authenticated;
revoke all on function public.record_project_item_event() from public, anon, authenticated;
revoke all on function public.handle_project_demotion() from public, anon, authenticated;
revoke all on function public.sync_project_action_reminder() from public, anon, authenticated;
